# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Rauch
email: mail@davidrauch.at
description: > # this means to ignore newlines until "baseurl:"
  I’m a student of Computer Science in Graz, Austria.
  I like tea, technology, movies, music, and politics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://davidrauch.at" # the base hostname & protocol for your site
twitter_username: _daver
github_username:  davidrauch

# Build settings
markdown: kramdown
exclude: [README.md, LICENSE]